shamefullyHoist: true

catalog:
  "@types/node": ^25.0.7
  "@types/picomatch": ^4.0.2
  "@vue/compiler-dom": ^3.5.26
  "@vue/compiler-sfc": ^3.5.26
  "@vue/language-core": ^3.2.2
  "@vue/shared": ^3.5.26
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.3.2
  eslint: ^9.39.2
  muggle-string: ^0.4.1
  oxc-parser: ^0.108.0
  oxc-walker: ^0.6.0
  picomatch: ^4.0.3
  tsdown: ^0.19.0
  vitest: ^4.0.17
